blank_issues_enabled: true
contact_links:
  - name: 功能讨论
    url: https://github.com/yourusername/chefmind/discussions/categories/ideas
    about: 讨论新功能和改进想法
  - name: 使用问题
    url: https://github.com/yourusername/chefmind/discussions/categories/q-a
    about: 提问关于如何使用ChefMind的问题
  - name: 文档反馈
    url: https://github.com/yourusername/chefmind/discussions/categories/docs
    about: 提供关于文档的反馈和建议